[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"
authors = ["cooljacwty"]
publish = false

[features]
try_trait_v2 = []

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
